# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "uuidtools", "2.2.0"
gem "iso-639", "0.3.5"
gem "ice_cube", "0.16.4"
gem "icalendar", "2.8.0"
gem "icalendar-recurrence", "1.1.3"
gem "date", "3.3.4"
gem "time", "0.2.0"
gem "stringio", "3.0.8"
gem "omnievent", "0.1.0.pre3"
gem "omnievent-icalendar", "0.1.0.pre5"
gem "omnievent-api", "0.1.0.pre2"
gem "omnievent-eventbrite", "0.1.0.pre2"
gem "omnievent-eventzilla", "0.1.0.pre2"
gem "omnievent-meetup", "0.1.0.pre1"
