# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'pkg-config', '1.5.6', {require: true}
gem 'observer', '0.1.2', {require: true}
gem 'rmagick', '6.0.1', {require: false}
gem 'prizm', '0.0.3', {require: true}
