# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'color', '1.8', {require: false}
gem 'colorscore', '0.0.5', {require: true}
gem 'rmagick', '4.2.2', {require: false}
gem 'prizm', '0.0.3', {require: true}
